### ISSUE TITLE
how to add a rectangular bend magnetic?

### ISSUE THREAD

**Issue by WeiWangHUST** [tomerikhaugen/LaTeX_LabBook#15]
I want add a rectangular bend magnetic.a weak vertical weak focusing is needed.but i cant constrcuct this magnetic field in Geant4.maybe i cant get the method.can you tell me how to do it?

**Comment by tomerikhaugen** [comment]
Not sure. This is not a relevant question for this project so I am going to close it. 

You should look at the application developer guide here: https://geant4.web.cern.ch/support/user_documentation 

Also look on the Geant4 forum here: https://geant4-forum.web.cern.ch/
